name: Build and Push Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for release
        if: github.event_name == 'release'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} \
            --push .

      - name: Build and push Docker image for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker buildx build \
            --platform linux/amd64 \
            --tag ghcr.io/${{ github.repository }}:dev_${COMMIT_SHA} \
            --push .
